<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegionDistrictSeeder extends Seeder
{
    public function run(): void
    {
        $regions = [
            [
                'name_uz' => "Toshkent shahri",
                'name_ru' => "город Ташкент",
                'name_en' => "Tashkent city",
                'districts' => [
                    // 2020 yildan keyin 12 ta tuman (Yangihayot qo'shildi, Hamza va boshqalar olib tashlandi)
                    ["Bektemir tumani",       "Бектемирский район",        "Bektemir district"],
                    ["Chilonzor tumani",      "Чиланзарский район",        "Chilanzar district"],
                    ["Mirobod tumani",        "Мирабадский район",         "Mirabad district"],
                    ["Mirzo Ulug'bek tumani", "Мирзо-Улугбекский район",   "Mirzo Ulugbek district"],
                    ["Olmazor tumani",        "Алмазарский район",         "Almazar district"],
                    ["Sergeli tumani",        "Сергелийский район",        "Sergeli district"],
                    ["Shayxontohur tumani",   "Шайхантахурский район",     "Shaykhantakhur district"],
                    ["Uchtepa tumani",        "Учтепинский район",         "Uchtepa district"],
                    ["Yakkasaroy tumani",     "Яккасарайский район",       "Yakkasaray district"],
                    ["Yangihayot tumani",     "Янгихаётский район",        "Yangihayot district"],
                    ["Yunusobod tumani",      "Юнусабадский район",        "Yunusabad district"],
                    ["Yashnobod tumani",      "Яшнободский район",         "Yashnabad district"],
                    ["Akmal Ikromov tumani",  "Акмал-Икрамовский район",   "Akmal Ikromov district"],
                    ["Qo'yliq tumani",        "Куйлюкский район",          "Kuylyuk district"],
                    ["Zangiota tumani",       "Зангиатинский район",       "Zangiata district"],
                    ["Bo'ka tumani",          "Букинский район",           "Buka district"],
                ],
            ],
            [
                'name_uz' => "Toshkent viloyati",
                'name_ru' => "Ташкентская область",
                'name_en' => "Tashkent region",
                'districts' => [
                    ["Angren shahri",          "город Ангрен",               "Angren city"],
                    ["Bekobod tumani",         "Бекабадский район",          "Bekabad district"],
                    ["Bo'stonliq tumani",      "Бостанлыкский район",        "Bostanliq district"],
                    ["Chinoz tumani",          "Чиназский район",            "Chinaz district"],
                    ["Oqqo'rg'on tumani",      "Аккурганский район",         "Akkurgan district"],
                    ["Ohangaron tumani",       "Ахангаранский район",        "Akhangaran district"],
                    ["Parkent tumani",         "Паркентский район",          "Parkent district"],
                    ["Piskent tumani",         "Пскентский район",           "Pskent district"],
                    ["Qibray tumani",          "Кибрайский район",           "Kibray district"],
                    ["Quyi Chirchiq tumani",   "Нижнечирчикский район",      "Lower Chirchiq district"],
                    ["Toshkent tumani",        "Ташкентский район",          "Tashkent district"],
                    ["Yuqori Chirchiq tumani", "Верхнечирчикский район",     "Upper Chirchiq district"],
                    ["Zangiota tumani",        "Зангиатинский район",        "Zangiata district"],
                    ["Bo'ka tumani",           "Букинский район",            "Buka district"],
                ],
            ],
            [
                'name_uz' => "Samarqand viloyati",
                'name_ru' => "Самаркандская область",
                'name_en' => "Samarkand region",
                'districts' => [
                    ["Samarqand shahri",   "город Самарканд",          "Samarkand city"],
                    ["Bulung'ur tumani",   "Булунгурский район",       "Bulungur district"],
                    ["Ishtixon tumani",    "Иштиханский район",        "Ishtikhon district"],
                    ["Jomboy tumani",      "Джамбайский район",        "Jomboy district"],
                    ["Kattaqo'rg'on tumani","Каттакурганский район",   "Kattakurgan district"],
                    ["Narpay tumani",      "Нарпайский район",         "Narpay district"],
                    ["Nurobod tumani",     "Нурабадский район",        "Nurabad district"],
                    ["Oqdaryo tumani",     "Акдарьинский район",       "Okdarya district"],
                    ["Pastdarg'om tumani", "Пастдаргомский район",     "Pastdargom district"],
                    ["Payariq tumani",     "Пайарыкский район",        "Payariq district"],
                    ["Qo'shrabot tumani",  "Кушрабатский район",       "Kushrabat district"],
                    ["Toyloq tumani",      "Тайлякский район",         "Taylyak district"],
                    ["Urgut tumani",       "Ургутский район",          "Urgut district"],
                ],
            ],
            [
                'name_uz' => "Andijon viloyati",
                'name_ru' => "Андижанская область",
                'name_en' => "Andijan region",
                'districts' => [
                    ["Andijon shahri",    "город Андижан",            "Andijan city"],
                    ["Asaka tumani",      "Асакинский район",         "Asaka district"],
                    ["Baliqchi tumani",   "Балыкчинский район",       "Balikchi district"],
                    ["Bo'z tumani",       "Бузский район",            "Boz district"],
                    ["Buloqboshi tumani", "Булакбашинский район",     "Buloqboshi district"],
                    ["Izboskan tumani",   "Избасканский район",       "Izbaskan district"],
                    ["Jalaquduq tumani",  "Джалакудукский район",     "Jalakuduk district"],
                    ["Xo'jaobod tumani",  "Ходжаабадский район",      "Khozhaabad district"],
                    ["Marhamat tumani",   "Мархаматский район",       "Mrkhamat district"],
                    ["Oltinko'l tumani",  "Алтынкульский район",      "Oltinkul district"],
                    ["Paxtaobod tumani",  "Пахтаабадский район",      "Pakhtaabad district"],
                    ["Qo'rg'ontepa tumani","Кургантепинский район",   "Kurgatepa district"],
                    ["Shahrixon tumani",  "Шахриханский район",       "Shahrikhan district"],
                    ["Ulug'nor tumani",   "Улугнорский район",        "Ulugnar district"],
                ],
            ],
            [
                'name_uz' => "Farg'ona viloyati",
                'name_ru' => "Ферганская область",
                'name_en' => "Fergana region",
                'districts' => [
                    ["Farg'ona shahri",  "город Фергана",            "Fergana city"],
                    ["Qo'qon shahri",    "город Коканд",             "Kokand city"],
                    ["Marg'ilon shahri", "город Маргилан",           "Margilan city"],
                    ["Bag'dod tumani",   "Багдадский район",         "Bagdad district"],
                    ["Beshariq tumani",  "Бешарыкский район",        "Beshariq district"],
                    ["Dang'ara tumani",  "Дангаринский район",       "Dangara district"],
                    ["Farg'ona tumani",  "Ферганский район",         "Fergana district"],
                    ["Furqat tumani",    "Фуркатский район",         "Furqat district"],
                    ["Oltiariq tumani",  "Алтыарыкский район",       "Oltiariq district"],
                    ["Oqtepa tumani",    "Актепинский район",        "Aktеpa district"],
                    ["Qo'shtepa tumani", "Куштепинский район",       "Kushtepa district"],
                    ["Rishton tumani",   "Риштанский район",         "Rishtan district"],
                    ["So'x tumani",      "Сохский район",            "Sokh district"],
                    ["Toshloq tumani",   "Ташлакский район",         "Tashlak district"],
                    ["Uchko'prik tumani","Учкупрюкский район",       "Uchkuprik district"],
                    ["O'zbekiston tumani","Узбекистанский район",    "Uzbekistan district"],
                    ["Yozyovon tumani",  "Язъяванский район",        "Yazyavan district"],
                ],
            ],
            [
                'name_uz' => "Namangan viloyati",
                'name_ru' => "Наманганская область",
                'name_en' => "Namangan region",
                'districts' => [
                    ["Namangan shahri",   "город Наманган",           "Namangan city"],
                    ["Chortoq tumani",    "Чартакский район",         "Chartak district"],
                    ["Chust tumani",      "Чустский район",           "Chust district"],
                    ["Kosonsoy tumani",   "Касансайский район",       "Kosonsoy district"],
                    ["Mingbuloq tumani",  "Мингбулакский район",      "Mingbulak district"],
                    ["Namangan tumani",   "Наманганский район",       "Namangan district"],
                    ["Norin tumani",      "Нарынский район",          "Naryn district"],
                    ["Pop tumani",        "Папский район",            "Pop district"],
                    ["To'raqo'rg'on tumani","Туракурганский район",   "Turakurgan district"],
                    ["Uchqo'rg'on tumani","Учкурганский район",       "Uchkurgan district"],
                    ["Uychi tumani",      "Уйчинский район",          "Uychi district"],
                    ["Yangiqo'rg'on tumani","Янгикурганский район",   "Yangikurgan district"],
                ],
            ],
            [
                'name_uz' => "Buxoro viloyati",
                'name_ru' => "Бухарская область",
                'name_en' => "Bukhara region",
                'districts' => [
                    ["Buxoro shahri",    "город Бухара",             "Bukhara city"],
                    ["Olot tumani",      "Алатский район",           "Alat district"],
                    ["Buxoro tumani",    "Бухарский район",          "Bukhara district"],
                    ["G'ijduvon tumani", "Гиждуванский район",       "Gijduvan district"],
                    ["Jondor tumani",    "Жандарский район",         "Jondor district"],
                    ["Kogon tumani",     "Каганский район",          "Kagan district"],
                    ["Qorako'l tumani",  "Каракульский район",       "Karakul district"],
                    ["Qorovulbozor tumani","Каравулбазарский район", "Karavulbazar district"],
                    ["Peshku tumani",    "Пешкунский район",         "Peshku district"],
                    ["Romitan tumani",   "Ромитанский район",        "Romitan district"],
                    ["Shofirkon tumani", "Шафирканский район",       "Shafirkan district"],
                    ["Vobkent tumani",   "Вабкентский район",        "Vabkent district"],
                ],
            ],
            [
                'name_uz' => "Xorazm viloyati",
                'name_ru' => "Хорезмская область",
                'name_en' => "Khorezm region",
                'districts' => [
                    ["Urganch shahri",    "город Ургенч",            "Urgench city"],
                    ["Bog'ot tumani",     "Багатский район",         "Bagat district"],
                    ["Gurlan tumani",     "Гурленский район",        "Gurlan district"],
                    ["Xonqa tumani",      "Ханкинский район",        "Khanka district"],
                    ["Xazorasp tumani",   "Хазараспский район",      "Khazarasp district"],
                    ["Xiva tumani",       "Хивинский район",         "Khiva district"],
                    ["Qo'shko'pir tumani","Кушкупырский район",      "Kushkupyr district"],
                    ["Shovot tumani",     "Шаватский район",         "Shavat district"],
                    ["Tuproqqal'a tumani","Тупраккалинский район",   "Tuprakqala district"],
                    ["Urganch tumani",    "Ургенчский район",        "Urgench district"],
                    ["Yangiariq tumani",  "Янгиарыкский район",      "Yangiariq district"],
                    ["Yangibozor tumani", "Янгибазарский район",     "Yangibazar district"],
                ],
            ],
            [
                'name_uz' => "Qashqadaryo viloyati",
                'name_ru' => "Кашкадарьинская область",
                'name_en' => "Kashkadarya region",
                'districts' => [
                    ["Qarshi shahri",    "город Карши",              "Karshi city"],
                    ["Chiroqchi tumani", "Чиракчинский район",       "Chirakchi district"],
                    ["Dehqonobod tumani","Дехканабадский район",     "Dehkanabad district"],
                    ["G'uzor tumani",    "Гузарский район",          "Guzar district"],
                    ["Kasbi tumani",     "Касбийский район",         "Kasbi district"],
                    ["Kitob tumani",     "Китабский район",          "Kitab district"],
                    ["Koson tumani",     "Косонский район",          "Koson district"],
                    ["Mirishkor tumani", "Миришкорский район",       "Mirishkor district"],
                    ["Muborak tumani",   "Мубарекский район",        "Mubarek district"],
                    ["Nishon tumani",    "Нишанский район",          "Nishan district"],
                    ["Qarshi tumani",    "Каршинский район",         "Karshi district"],
                    ["Qamashi tumani",   "Камашинский район",        "Kamashi district"],
                    ["Shahrisabz tumani","Шахрисабзский район",      "Shahrisabz district"],
                    ["Yakkabog' tumani", "Яккабагский район",        "Yakkabag district"],
                ],
            ],
            [
                'name_uz' => "Surxondaryo viloyati",
                'name_ru' => "Сурхандарьинская область",
                'name_en' => "Surkhandarya region",
                'districts' => [
                    ["Termiz shahri",    "город Термез",             "Termez city"],
                    ["Angor tumani",     "Ангорский район",          "Angor district"],
                    ["Bandixon tumani",  "Бандиханский район",       "Bandikhan district"],
                    ["Boysun tumani",    "Байсунский район",         "Baisun district"],
                    ["Denov tumani",     "Денауский район",          "Denau district"],
                    ["Jarqo'rg'on tumani","Джаркурганский район",    "Jarkurgan district"],
                    ["Muzrabot tumani",  "Музрабатский район",       "Muzrabat district"],
                    ["Oltinsoy tumani",  "Алтынсайский район",       "Oltinsoy district"],
                    ["Qiziriq tumani",   "Кизирикский район",        "Kizirik district"],
                    ["Qo'mko'rg'on tumani","Кумкурганский район",    "Kumkurgan district"],
                    ["Sariosiyo tumani", "Сариасийский район",       "Sariasiya district"],
                    ["Sherobod tumani",  "Шерабадский район",        "Sherabad district"],
                    ["Sho'rchi tumani",  "Шурчинский район",         "Shurchi district"],
                    ["Termiz tumani",    "Термезский район",         "Termez district"],
                    ["Uzun tumani",      "Узунский район",           "Uzun district"],
                ],
            ],
            [
                'name_uz' => "Jizzax viloyati",
                'name_ru' => "Джизакская область",
                'name_en' => "Jizzakh region",
                'districts' => [
                    ["Jizzax shahri",         "город Джизак",              "Jizzakh city"],
                    ["Arnasoy tumani",         "Арнасайский район",         "Arnasay district"],
                    ["Baxmal tumani",          "Бахмальский район",         "Bakhmal district"],
                    ["Do'stlik tumani",        "Дустликский район",         "Dustlik district"],
                    ["Forish tumani",          "Фаришский район",           "Farish district"],
                    ["G'allaorol tumani",      "Галляаральский район",      "Gallaorol district"],
                    ["Jizzax tumani",          "Джизакский район",          "Jizzakh district"],
                    ["Mirzacho'l tumani",      "Мирзачульский район",       "Mirzachul district"],
                    ["Paxtakor tumani",        "Пахтакорский район",        "Pakhtakor district"],
                    ["Sharof Rashidov tumani", "Шараф-Рашидовский район",   "Sharof Rashidov district"],
                    ["Yangiobod tumani",       "Янгиабадский район",        "Yangiobod district"],
                    ["Zafarobod tumani",       "Зафарабадский район",       "Zafarabad district"],
                    ["Zarbdor tumani",         "Зарбдорский район",         "Zarbdor district"],
                ],
            ],
            [
                'name_uz' => "Sirdaryo viloyati",
                'name_ru' => "Сырдарьинская область",
                'name_en' => "Syrdarya region",
                'districts' => [
                    ["Guliston shahri",  "город Гулистан",           "Gulistan city"],
                    ["Boyovut tumani",   "Баяутский район",          "Bayaut district"],
                    ["Guliston tumani",  "Гулистанский район",       "Gulistan district"],
                    ["Xovos tumani",     "Хавастский район",         "Khavast district"],
                    ["Mirzaobod tumani", "Мирзаабадский район",      "Mirzaabad district"],
                    ["Oqoltin tumani",   "Акалтынский район",        "Akaltyn district"],
                    ["Sardoba tumani",   "Сардобинский район",       "Sardoba district"],
                    ["Sayxunobod tumani","Сайхунабадский район",     "Saikhunabad district"],
                    ["Sirdaryo tumani",  "Сырдарьинский район",      "Syrdarya district"],
                ],
            ],
            [
                'name_uz' => "Navoiy viloyati",
                'name_ru' => "Навоийская область",
                'name_en' => "Navoiy region",
                'districts' => [
                    ["Navoiy shahri",   "город Навои",              "Navoiy city"],
                    ["Karmana tumani",  "Карманинский район",       "Karmana district"],
                    ["Konimex tumani",  "Канимехский район",        "Kanimekh district"],
                    ["Navbahor tumani", "Навбахорский район",       "Navbakhor district"],
                    ["Nurota tumani",   "Нуратинский район",        "Nurata district"],
                    ["Qiziltepa tumani","Кызылтепинский район",     "Kiziltepa district"],
                    ["Tomdi tumani",    "Томдинский район",         "Tomdi district"],
                    ["Uchquduq tumani", "Учкудукский район",        "Uchkuduk district"],
                    ["Xatirchi tumani", "Хатырчинский район",       "Khatyrchi district"],
                ],
            ],
            [
                'name_uz' => "Qoraqalpog'iston Respublikasi",
                'name_ru' => "Республика Каракалпакстан",
                'name_en' => "Republic of Karakalpakstan",
                'districts' => [
                    ["Nukus shahri",      "город Нукус",              "Nukus city"],
                    ["Amudaryo tumani",   "Амударьинский район",      "Amudarya district"],
                    ["Beruniy tumani",    "Беруниский район",         "Beruni district"],
                    ["Chimboy tumani",    "Чимбайский район",         "Chimboy district"],
                    ["Ellikkala tumani",  "Элликкалинский район",     "Ellikkala district"],
                    ["Kegeyli tumani",    "Кегейлийский район",       "Kegeyli district"],
                    ["Mo'ynoq tumani",    "Муйнакский район",         "Muynak district"],
                    ["Nukus tumani",      "Нукусский район",          "Nukus district"],
                    ["Qanliko'l tumani",  "Канлыкульский район",      "Kanlykul district"],
                    ["Qo'ng'irot tumani", "Кунградский район",        "Kungrad district"],
                    ["Qorao'zak tumani",  "Караузякский район",       "Karauzyak district"],
                    ["Shumanay tumani",   "Шуманайский район",        "Shumanay district"],
                    ["Taxtako'pir tumani","Тахтакупырский район",     "Takhtakupyr district"],
                    ["To'rtko'l tumani",  "Турткульский район",       "Turtkul district"],
                    ["Xo'jayli tumani",   "Ходжейлийский район",      "Khojeli district"],
                ],
            ],
        ];

        foreach ($regions as $regionData) {
            $regionId = DB::table('regions')->insertGetId([
                'name_uz'    => $regionData['name_uz'],
                'name_ru'    => $regionData['name_ru'],
                'name_en'    => $regionData['name_en'],
                'is_active'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            $districts = array_map(fn($d) => [
                'region_id'  => $regionId,
                'name_uz'    => $d[0],
                'name_ru'    => $d[1],
                'name_en'    => $d[2],
                'is_active'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], $regionData['districts']);

            DB::table('districts')->insert($districts);
        }

        $this->command->info('✓ ' . count($regions) . ' ta viloyat va tumanlar yaratildi!');
    }
}
